import type { Metadata } from 'next';
import Link from 'next/link';
import { LegalArticle } from '@/components/legal/legal-article';
import { JsonLd } from '@/components/seo/json-ld';
import { SITE } from '@/config/site';
import { crumbsFor, legalGraph } from '@/lib/schema';

const description =
  'PostRoast terms: the roast is an opinion, plans have caps, we do not post to X for you, and the service is provided as-is.';

export const metadata: Metadata = {
  title: 'Terms of use',
  description,
  alternates: { canonical: '/terms' },
  openGraph: {
    title: 'Terms of use | PostRoast',
    description,
    url: `${SITE.url}/terms`,
  },
};

export default function TermsPage() {
  return (
    <>
      <JsonLd data={legalGraph('/terms', 'Terms of use', description)} />
      <LegalArticle kicker="Legal" title="Terms of use" crumbs={crumbsFor('/terms', 'Terms')}>
        <section>
          <h2>Agreement</h2>
          <p>
            These terms govern your use of PostRoast at www.postroast.app, including Roast, Studio,
            Ideas, Desk, and public roast cards. By creating an account or using the service, you
            agree to them. If you do not, do not use the product.
          </p>
          <p>
            PostRoast is operated by Audiencon. Questions go to{' '}
            <a
              href={SITE.founder.url}
              className="underline decoration-white/20 underline-offset-4 hover:text-white"
              rel="noopener noreferrer"
            >
              {SITE.founder.handle}
            </a>{' '}
            on X.
          </p>
        </section>

        <section>
          <h2>What PostRoast is</h2>
          <p>
            PostRoast is a writing tool. You paste an X or Twitter draft. We return a roast, four
            scores (Engage, Warmth, Viral, Payout), and rewrite options. Studio is a workspace for
            threads and critique. Ideas suggests drafts worth roasting.
          </p>
          <p>
            PostRoast does not post, schedule, or manage your X account. Compose on X opens a draft
            in X with the first post. That is a link, not posting permission.
          </p>
        </section>

        <section>
          <h2>Accounts</h2>
          <p>
            You need an account to roast. You are responsible for the email or sign-in method you
            use and for activity under that account. Do not share a login. We can close an account
            that abuses the service, evades caps, or pastes content we are not willing to store.
          </p>
        </section>

        <section>
          <h2>Plans, caps, and billing</h2>
          <p>Current published caps, as of {SITE.legalUpdatedLabel}:</p>
          <ul>
            <li>Free (Roast): 10 roasts a day, 3 saved drafts, 8 critiques a day.</li>
            <li>Pro ($19/month): unlimited roasts and roast history. Draft and critique caps stay.</li>
            <li>Studio ($32/month): unlimited roasts, drafts, and critique.</li>
            <li>Founder ($199 once): lifetime Studio. Limited to 100 seats, then it closes.</li>
          </ul>
          <p>
            Paid plans are billed through Stripe. Taxes may apply. We can change prices or caps
            with notice on the site. A price change does not rewrite a Founder license already
            purchased. Refunds are handled case by case; unused time on a canceled monthly plan is
            not automatically refunded.
          </p>
        </section>

        <section>
          <h2>The roast is an opinion</h2>
          <p>
            Scores, roasts, rewrites, Ideas, and critique are generated by software. They are not a
            promise of reach, followers, impressions, or Original Content Rewards payouts. X makes
            its own ranking and payment decisions. You decide what to post.
          </p>
        </section>

        <section>
          <h2>Your drafts and our license</h2>
          <p>
            You keep whatever rights you already have in the text you paste. You grant PostRoast a
            limited license to process that text so we can roast it, score it, rewrite it, save
            history, and — only if you click share — publish a roast card.
          </p>
          <p>
            Do not paste secrets, passwords, private keys, unpublished financials you cannot afford
            to store, or anyone else&apos;s confidential material. Model providers that generate
            the roast will see the draft.
          </p>
        </section>

        <section>
          <h2>Acceptable use</h2>
          <p>Do not use PostRoast to:</p>
          <ul>
            <li>Break the law, or generate content you intend to use to break the law.</li>
            <li>Attack, impersonate, or harass a person in a way that is illegal.</li>
            <li>Scrape, overload, or reverse the service beyond normal use.</li>
            <li>Resell raw model output as if it were a human edit you performed.</li>
          </ul>
        </section>

        <section>
          <h2>Sponsorships</h2>
          <p>
            Sponsorships appear only when a slot is sold. Paying users do not see ads. We can
            refuse or remove a placement that fights the product.
          </p>
        </section>

        <section>
          <h2>As-is, liability, and changes</h2>
          <p>
            The service is provided as-is. We do not warrant uninterrupted uptime, perfect scores,
            or that a rewrite will perform. To the extent the law allows, PostRoast is not liable
            for lost profits, lost followers, or damages that come from a post you chose to publish.
            If a court finds us liable anyway, that amount is capped at the fees you paid us in the
            twelve months before the claim, or $50 if you paid nothing.
          </p>
          <p>
            We can change these terms. The date at the top is the current version. Continued use
            after a change is acceptance of the new terms. Either of us can stop: you can close the
            account; we can suspend or end access if you break these terms or if we shut the
            product down.
          </p>
          <p>
            These terms are the operating rules of the product, not personalized legal advice. If
            something here conflicts with a law that cannot be waived, that law wins for that
            point.
          </p>
        </section>

        <section>
          <h2>Related</h2>
          <p>
            How we handle drafts and processors is in the{' '}
            <Link href="/privacy" className="underline decoration-white/20 underline-offset-4 hover:text-white">
              Privacy policy
            </Link>
            . Product questions are on the{' '}
            <Link href="/faq" className="underline decoration-white/20 underline-offset-4 hover:text-white">
              FAQ
            </Link>
            .
          </p>
        </section>
      </LegalArticle>
    </>
  );
}
